ingress:
  # allows you to specify custom hosts
  customHosts:
    # specify your ngrok custom domain here
    # such as
    #    hook: "myuniqueid.ngrok.io
    # so that webhooks from, say, github.com, will work to your local laptop
    hook: "78c9-2401-4900-3bed-dd58-a0a2-9758-fcf8-bd5d.ngrok.io"
    bucketrepo: "5412-106-196-7-133.ngrok.io"

kaniko:
  # lets support insecure docker registries so that we
  # can use the local docker-registry chart
  flags: "--insecure"